{
 "title": "SE2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ebpf_exporter_syscalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ebpf_exporter_syscalls_total{syscall=\"write\"}",
     "legendFormat": "{{syscall}}"
    },
    {
     "expr": "ebpf_exporter_syscalls_total{syscall=\"read\"}",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"grafana\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_cpu_usage_seconds_total{name=\"prometheus\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "prometheus_network_traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"prometheus\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_bytes_total{name=\"prometheus\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "host_memory_utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ebpf_exporter_bio_latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "grafana_memory_utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expression": "$A/(1024*1024)", "type": "math" }
   ]
  },
  {
   "title": "host_cpu_utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ebpf_exporter_llc_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "ebpf_exporter_llc_misses_total", "legendFormat": "__auto" }
   ]
  }
 ]
}